language: python
# Supported Python versions
python:
  - "3.5"
  - "3.6"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - coverage run --source authors -m pytest
  - python -m coverage report -m

after_success:
  # Run coveralls
  - coveralls
