language: python
# Supported Python versions
python:
  - "3.6"

# Install dependencies
install:
 - pip install -r requirements.txt

services:
 - postgresql


# Run tests
before_script:
 - psql -c 'create database fulldeck;' -U postgres
 - psql -c "ALTER USER postgres WITH PASSWORD 'fulldeck';" -U postgres
 - python manage.py makemigrations
 - python manage.py migrate
script:
 - coverage run --source=authors/apps manage.py test

 - python -m coverage report -m

 # Run coveralls
after_success:
 - coveralls
